version: "3.9"
services:
  server:
    build: .
    ports:
      - 4567:4567

  client:
    build:
      context: inst/app
      args:
        NEXT_PUBLIC_SERVER_URL: http://server:4567
    ports:
      - 3000:3000
